public enum Audios
{
    bate_pared,
    bath_al_aire,
    disparo_laser,
    enemigo_explota,
    granada,
    habilidad_cancelada,
    habilidad_comprada,
    matar_enemigo_bath,
    menu,
    nivel1,
    nivel2,
    respiracion_agitada,
    respiracion_media,
    respiracion_normal,
    menu_atras,
    menu_clic,
    menu_slide,
    pausa_on,
    pausa_off,
    musica_on,
    musica_off
}